# Generated by Django 3.0.3 on 2020-02-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_approval_score',
            field=models.IntegerField(default=70),
        ),
    ]
